require("gpadanyig.plugins-setup")
require("gpadanyig.core.global")
require("gpadanyig.core.options")
require("gpadanyig.core.keymaps")
require("gpadanyig.core.colorscheme")
require("gpadanyig.plugins-init")
